<a href="https://colab.research.google.com/github/SattuSupCodes/PythonJournal/blob/main/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
array = np.array([[[1,2,3], [4,5,6], [7,8,9]],
          [[4,7,1], [5,3,9], [8,2,5]],
          [[3,6,8], [8,5,3], [6,0,4]]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmin(array))
print(np.sum(array, axis = 0))

132
4.888888888888889
2.528845928164676
6.395061728395062
0
9
25
25
[[ 8 15 12]
 [17 13 18]
 [21 10 18]]


In [11]:
print(array.ndim)
print(array[1,1,0])
sum = array[0,0,0]+array[0,0,2]
print(sum)

3
5
4


In [26]:
#slicing

# array[start:end:step]

ar = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12],[13,14,15,16]])

# print(ar[:2]) #row
#column
print(ar[:,1::2])

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
