<a href="https://colab.research.google.com/github/SattuSupCodes/PythonJournal/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [7]:
#scalar
scalar = torch.tensor(7)
print(scalar)
scalar.ndim #has no dimensions

scalar.item() #get tensor back as int

#vector

vector = torch.tensor([7,7])
print(vector)
vector.ndim



tensor(7)
tensor([7, 7])


1

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,6]])
MATRIX.ndim

2

In [12]:
#TENSORS
TENSOR = torch.tensor([[[7,8,6],[7,5,2],[8,5,1]]])

TENSOR
TENSOR.ndim


3

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

#RANDOM TENSORS
They are important because the way many neural networks learn is that they start with tensors full of randomnumbers and then adjust those random numbers to better represent the data.

```start with random numbers -> look at data -> update random numbers -> look at data -> update ```

In [20]:
random_tensor = torch.rand(3,4) #SIZE (3,4)

print(random_tensor)

tensor([[0.5275, 0.7666, 0.8424, 0.8106],
        [0.4904, 0.8085, 0.3949, 0.0128],
        [0.0593, 0.4937, 0.1883, 0.9851]])


In [23]:
random_image_size_tensor = torch.rand(size=(3,224,224) )#height, width, color channel
print(random_image_size_tensor)

tensor([[[9.6329e-01, 5.0680e-01, 1.3065e-01,  ..., 4.0420e-01,
          3.7858e-01, 2.0049e-01],
         [8.7668e-02, 8.9744e-01, 5.4320e-01,  ..., 9.2008e-01,
          8.1740e-01, 5.3518e-01],
         [2.0945e-02, 2.2821e-03, 6.8168e-01,  ..., 5.6733e-02,
          7.8859e-01, 4.2080e-01],
         ...,
         [8.5714e-02, 5.9083e-01, 1.9211e-01,  ..., 5.4687e-01,
          1.5458e-01, 2.3942e-01],
         [3.0382e-01, 8.7858e-01, 8.7738e-01,  ..., 6.9465e-01,
          6.3398e-02, 7.0475e-01],
         [7.9738e-01, 7.0329e-02, 9.6849e-01,  ..., 7.8183e-01,
          2.9734e-01, 7.3333e-01]],

        [[6.3732e-01, 7.6461e-01, 9.0199e-01,  ..., 4.3187e-01,
          5.2637e-01, 5.2344e-01],
         [5.5721e-01, 2.6954e-01, 5.8319e-01,  ..., 8.9222e-02,
          4.6598e-01, 5.1699e-01],
         [5.9264e-01, 9.3112e-01, 3.0668e-01,  ..., 2.3593e-01,
          6.2347e-01, 1.4206e-01],
         ...,
         [9.1508e-01, 1.8131e-01, 8.9572e-01,  ..., 2.5239e-01,
          2.509

In [25]:
#creating a range of tensors and tensors like

torch.arange(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#MATRIX MULTIPLICATION

Two main ways to multiply matrices in neural network and deep learning

1. Element-wise
2. Matrix multiplication (dot product)

In [27]:
#1
tensor = torch.tensor([1,2,4])
tensor * tensor

tensor([ 1,  4, 16])

In [28]:
#2
torch.matmul(tensor,tensor)

tensor(21)